# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 407bb122778ae6c96b7b49800a9bfefb08bc4ac9467dfbe24de4e7434e64db68c1e744ed2d106a11fad9aa57d88cac0cc9193a9d49a87888e5e31f9bede22dce

test:
  secret_key_base: 1a7fa67c1c921c5c105120d3000dc38ade44fbf6dd13cdf5820467364cfa753b0213f0604471c4e9cf42b4ae34d74c9f1ec9e7a0f18e43d9d6f80cf98c74bd5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
